wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.1
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721769219
    t:
      1:
      - 55
      - 95
      - 97
      - 105
      2:
      - 55
      - 95
      - 97
      - 105
      3:
      - 23
      4: 3.9.1
      5: 0.17.5
      8:
      - 5
      13: darwin-x86_64
